In [4]:
import numpy as np
a = np.random.randn(5)

In [5]:
print(a)

[ 0.51989869  0.86065856 -0.68900702  1.59437777  0.51669413]


In [6]:
#Don't use this because it is (5,) you want (5,1) or (1,5) in this scenario
print(a.shape)

(5,)


In [7]:
print(a.T)

[ 0.51989869  0.86065856 -0.68900702  1.59437777  0.51669413]


In [8]:
print(np.dot(a,a.T))

4.29477176348


In [9]:
a = np.random.randn(5,1)
print(a)

[[-0.92035946]
 [-0.22700635]
 [-0.38631681]
 [-0.26578702]
 [-1.44028638]]


In [10]:
print(a.T)

[[-0.92035946 -0.22700635 -0.38631681 -0.26578702 -1.44028638]]


In [11]:
print(np.dot(a,a.T))

[[ 0.84706153  0.20892744  0.35555033  0.2446196   1.3255812 ]
 [ 0.20892744  0.05153188  0.08769637  0.06033534  0.32695415]
 [ 0.35555033  0.08769637  0.14924068  0.10267799  0.55640684]
 [ 0.2446196   0.06033534  0.10267799  0.07064274  0.38280943]
 [ 1.3255812   0.32695415  0.55640684  0.38280943  2.07442487]]


In [15]:
assert(a.shape == (5,1))

In [16]:
#This will throw an error, will be good to check this
assert(a.shape == (5,2))

AssertionError: 

In [20]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a * b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [21]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [23]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [24]:
c.shape

(3, 3)